![](Capture29.png)

Author : Shanmugaraj Kamaraj

In [1]:
!pip install numpy
# to install numpy

NUmpy is used for calculating high dimensional arrays

It is faster than normal list in python
Efficient and also, convinent to use

In [2]:
#Numpy array looks like
[[2,3],[4,5],[2,7]]

[[2, 3], [4, 5], [2, 7]]

##### Terms used in Numpy

In [3]:
axes - Each dimension(rows) in the numpy array
rank - Number of axes i.e., number of axes in the numpy array
ndarray - It is nothing but a word that tells the type numpy array is ndarray

SyntaxError: invalid syntax (<ipython-input-3-c29d3eafd33d>, line 1)

![](Capture30.png)

In [4]:
import numpy as np 
  
n = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]] ) 
  
n

array([[1, 2, 3],
       [4, 2, 5]])

In [5]:
type(n)

numpy.ndarray

In [6]:
dir(n)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [7]:
print("No. of dimensions: ", n.ndim) 
  
print("Shape of array: ", n.shape) 
  
print("Size of array: ", n.size) 
  
print("Array stores elements of type: ", n.dtype)  #dtype tells the type of elements in the ndarray

No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [8]:
a1 = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float') 
print(type(a1))
a1

<class 'numpy.ndarray'>


array([[1., 2., 4.],
       [5., 8., 7.]])

In [9]:
a2 = np.zeros((2, 2))
print(type(a2))
a2

<class 'numpy.ndarray'>


array([[0., 0.],
       [0., 0.]])

In [10]:
a3 = np.ones((2, 2))
print(type(a3))
a3 # it is float

<class 'numpy.ndarray'>


array([[1., 1.],
       [1., 1.]])

In [11]:
a3 = np.ones((2, 2), dtype = 'int')
print(type(a3))
a3 # it is integer

<class 'numpy.ndarray'>


array([[1, 1],
       [1, 1]])

In [12]:
a4 = np.empty((2, 2), dtype = 'int')
print(type(a4))
a4 # These values may or may not be zeros

<class 'numpy.ndarray'>


array([[ -913200578, -1876754600],
       [ 1334583457,  1982522981]])

In [13]:
transpose = a4.T # Transpose of array
transpose

array([[ -913200578,  1334583457],
       [-1876754600,  1982522981]])

![](Capture31.png)

In [14]:
a5 = np.random.random((2, 2)) 
a5

array([[0.90982319, 0.42014321],
       [0.19813221, 0.42182015]])

In [15]:
a5 = np.random.random((2, 2)) 
a5

array([[0.96939348, 0.86948479],
       [0.31451518, 0.6257017 ]])

In [16]:
Every time we run np.random.random() function it return different values.
What if, we want same every time we call this function..

SyntaxError: invalid syntax (<ipython-input-16-ea0b17f76fbe>, line 1)

In [17]:
a5 = np.random.seed(0)
a5 = np.random.rand(4)
a5
# random function not generates the random values instead it generate pseudo-random numbers
# If seed is set to a particular value, then the random function generates same value every time we call

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [18]:
np.random.seed(0)
a5 = np.random.rand(4)
a5

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [19]:
np.random.seed(10)
a5 = np.random.rand(4)
a5

array([0.77132064, 0.02075195, 0.63364823, 0.74880388])

In [20]:
np.random.seed(100)
a5 = np.random.rand(4)
a5

array([0.54340494, 0.27836939, 0.42451759, 0.84477613])

In [21]:
nparray = np.arange(0, 5) # Creates 5 values
nparray

array([0, 1, 2, 3, 4])

In [22]:
nparray = np.arange(0, 5, 0.1) # generates ndarray starting from 0 to 5 at interval of 0.1
nparray

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [23]:
nparray = np.arange(0, 5, 2, dtype=float) # generates ndarray starting from 0 to 5 at interval of 2
nparray

array([0., 2., 4.])

In [24]:
a6 = np.linspace(0, 2, 6) # It generates equally spaced samples in the closed interval
a6

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [25]:
a6.shape

(6,)

In [26]:
reshape_a6 = a6.reshape(2, 3) 
reshape_a6

array([[0. , 0.4, 0.8],
       [1.2, 1.6, 2. ]])

In [27]:
flatten_a6 = reshape_a6.flatten() # Flatten array - reshaped the array into (1,)
flatten_a6

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

![](Capture32.PNG)

In [28]:
flatten_a6[0:1] # [starting index:ending index]

array([0.])

In [29]:
flatten_a6[0:4] # [starting index:ending index]

array([0. , 0.4, 0.8, 1.2])

In [30]:
flatten_a6[0:4:2] # [starting index:ending index:step interval]

array([0. , 0.8])

In [31]:
full = np.array([[2,3,4,5],
       [3,6,7,8],
       [0,66,43,24],
       [55,64,77,88],])
print(type(full))
print(full)

<class 'numpy.ndarray'>
[[ 2  3  4  5]
 [ 3  6  7  8]
 [ 0 66 43 24]
 [55 64 77 88]]


In [32]:
full[0:4,0:3] 
# [axes starting index:axes ending index, row's starting index:row's ending index]

array([[ 2,  3,  4],
       [ 3,  6,  7],
       [ 0, 66, 43],
       [55, 64, 77]])

In [33]:
full[0:4:2,0:4:2] 
# [axes starting index:axes ending index:axes step interval, row's starting index:row's ending index:row's step interval]

array([[ 2,  4],
       [ 0, 43]])

In [34]:
full>0 # Returns True or False if the condition check with all the elements

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
full>2

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
full[full>2]

array([ 3,  4,  5,  3,  6,  7,  8, 66, 43, 24, 55, 64, 77, 88])

![](Capture33.PNG)

In [37]:
full + 10

array([[12, 13, 14, 15],
       [13, 16, 17, 18],
       [10, 76, 53, 34],
       [65, 74, 87, 98]])

In [38]:
full ** 2

array([[   4,    9,   16,   25],
       [   9,   36,   49,   64],
       [   0, 4356, 1849,  576],
       [3025, 4096, 5929, 7744]], dtype=int32)

In [39]:
new_axes = np.array([1, 2, 3, 4])
                    
full[0:2] + new_axes

array([[ 3,  5,  7,  9],
       [ 4,  8, 10, 12]])

In [40]:
import time
l =[1,2,3]
ll = [1,2,3]
result = []
if(len(l)==len(ll)):
    for i in range(len(l)):
        result.append(l[i] * ll[i])
result

[1, 4, 9]

In [41]:
list1 = range(10)
list2 = range(10)

list_result = []
start = time.time()
list_result = [sum(i) for i in zip(list1, list2)] 

print("Time taken for list multiplication in seconds: ",(time.time()-start))

n1=np.arange(10)
n2=np.arange(10)

start= time.time()
result = n1 * n2
print("Time taken for numpy multiplication in seconds: ", (time.time()-start))


Time taken for list multiplication in seconds:  0.0
Time taken for numpy multiplication in seconds:  0.0


In [42]:
list1 = range(10000000)
list2 = range(10000000)

start = time.time()
list_result = [sum(i) for i in zip(list1, list2)] 

print("Time taken for list multiplication in seconds: ",(time.time()-start))

n1=np.arange(10000000)
n2=np.arange(10000000)

start= time.time()
result = n1 * n2
print("Time taken for numpy multiplication in seconds: ", (time.time()-start))


Time taken for list multiplication in seconds:  2.5661468505859375
Time taken for numpy multiplication in seconds:  0.016000986099243164


In [43]:
np.sin(n1) # Returns the sin values of ndarray n1

array([ 0.        ,  0.84147098,  0.90929743, ..., -0.28830516,
        0.64996899,  0.99066465])

In [44]:
np.cos(n1) # Returns the cos values of ndarray n1

array([ 1.        ,  0.54030231, -0.41614684, ...,  0.95753858,
        0.75996073, -0.13632152])

In [45]:
np.sqrt(n1) # Returns the squre rootvalues of ndarray n1

array([0.00000000e+00, 1.00000000e+00, 1.41421356e+00, ...,
       3.16227719e+03, 3.16227734e+03, 3.16227750e+03])

In [46]:
full

array([[ 2,  3,  4,  5],
       [ 3,  6,  7,  8],
       [ 0, 66, 43, 24],
       [55, 64, 77, 88]])

In [47]:
np.sort(full)

array([[ 2,  3,  4,  5],
       [ 3,  6,  7,  8],
       [ 0, 24, 43, 66],
       [55, 64, 77, 88]])

In [48]:
np.sort(full, axis = 1) # sort in row

array([[ 2,  3,  4,  5],
       [ 3,  6,  7,  8],
       [ 0, 24, 43, 66],
       [55, 64, 77, 88]])

In [49]:
np.sort(full, axis = 0) # sort by column

array([[ 0,  3,  4,  5],
       [ 2,  6,  7,  8],
       [ 3, 64, 43, 24],
       [55, 66, 77, 88]])

In [50]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),('Galahad', 1.7, 38)]
a7 = np.array(values, dtype=dtype) 
np.sort(a7, order=[ 'height'])            

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [51]:
print(full)
print(full.shape)

[[ 2  3  4  5]
 [ 3  6  7  8]
 [ 0 66 43 24]
 [55 64 77 88]]
(4, 4)


In [52]:
print(np.expand_dims(full, axis=0)) # Expending dimension in numpy array
print(np.expand_dims(full, axis=0).shape)

[[[ 2  3  4  5]
  [ 3  6  7  8]
  [ 0 66 43 24]
  [55 64 77 88]]]
(1, 4, 4)


![](Capture34.PNG)

In [53]:
n3 = np.array([[41, 77], 
              [30, 77]]) 
  
n4 = np.array([[15, 49], 
              [56, 85]]) 
print(n3)
print("-----")
print(n4)

[[41 77]
 [30 77]]
-----
[[15 49]
 [56 85]]


In [54]:
np.vstack((n3, n4)) # vertical stacking

array([[41, 77],
       [30, 77],
       [15, 49],
       [56, 85]])

In [55]:
np.hstack((n3, n4)) # horizontal stacking

array([[41, 77, 15, 49],
       [30, 77, 56, 85]])

In [56]:
n5 = np.array([1, 2])
np.column_stack((n3, n5)) 

array([[41, 77,  1],
       [30, 77,  2]])

In [57]:
n6 = np.array([4,5])
np.column_stack((n3, n4))

array([[41, 77, 15, 49],
       [30, 77, 56, 85]])

In [58]:
np.concatenate((n5, n6),)

array([1, 2, 4, 5])

In [59]:
np.concatenate((n5, n6), 0)

array([1, 2, 4, 5])

![](Capture35.PNG)

In [60]:
x = np.array([[1, 2, 3, 4, 5, 6], 
              [7, 8, 9, 10, 20, 30]]) 

h_split = np.hsplit(x, 3) # split the ndarray x into 3 ndarray in horizontal
h_split 

[array([[1, 2],
        [7, 8]]), array([[ 3,  4],
        [ 9, 10]]), array([[ 5,  6],
        [20, 30]])]

In [61]:
for i in h_split:
    print(i)
    print(type(i))

[[1 2]
 [7 8]]
<class 'numpy.ndarray'>
[[ 3  4]
 [ 9 10]]
<class 'numpy.ndarray'>
[[ 5  6]
 [20 30]]
<class 'numpy.ndarray'>


In [62]:
v_split = np.vsplit(x, 3) # split the ndarray x into 3 ndarray in vertical

v_split 
# Gives error because of spliting x into 3 ndarray is not equal in each ndarray

ValueError: array split does not result in an equal division

In [63]:
v_split = np.vsplit(x, 2) # split the ndarray x into 2 ndarray in vertical which is equal in each ndarray

v_split 

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 20, 30]])]

In [64]:
for i in v_split:
    print(i)
    print(type(i))

[[1 2 3 4 5 6]]
<class 'numpy.ndarray'>
[[ 7  8  9 10 20 30]]
<class 'numpy.ndarray'>


In [65]:
a_split = np.array_split(x, 2) # split the ndarray x into 2 ndarray 

a_split 

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 20, 30]])]

In [66]:
a_split = np.array_split(x, 3) # split the ndarray x into 3 ndarray 

a_split 

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 20, 30]]),
 array([], shape=(0, 6), dtype=int32)]

In [67]:
for i in a_split:
    print(i)
    print(type(i))

[[1 2 3 4 5 6]]
<class 'numpy.ndarray'>
[[ 7  8  9 10 20 30]]
<class 'numpy.ndarray'>
[]
<class 'numpy.ndarray'>


In [68]:
a_split = np.array_split(x, 2, axis = 1) # split the ndarray x into 2 ndarray and, the axis = 1 which means vertical
# by default, axis = 0 which is horizontal

a_split 

[array([[1, 2, 3],
        [7, 8, 9]]), array([[ 4,  5,  6],
        [10, 20, 30]])]

![](Capture36.png)

In [69]:
iterate = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
iterate

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
# If we need to get every element, the simple option is for loop
for i in iterate:
    for ii in i:
        print(ii)


1
2
3
4
5
6
7
8
9


In [71]:
for x in np.nditer(iterate, order='C'):
    print(x)
# without using secound loop, the numpy have the np.nditer() function

1
2
3
4
5
6
7
8
9


In [72]:
for x in np.nditer(iterate, order='F'):
    print(x)

1
4
7
2
5
8
3
6
9


##### External_loop flag in array while iterating

In [73]:
for x in np.nditer(iterate, flags=['external_loop'],order='C'):
    print(x)

[1 2 3 4 5 6 7 8 9]


In [74]:
for x in np.nditer(iterate, flags=['external_loop'],order='F'):
    print(x)

[1 4 7]
[2 5 8]
[3 6 9]


##### Modify array values while iterating

In [75]:
for x in np.nditer(iterate, op_flags=['readwrite']):
    x[...] = x * 2

In [76]:
x

array(18)

In [77]:
x = np.array([[1, 2, 3, 4, 5, 6], 
              [7, 8, 9, 10, 20, 30]]) 

y = np.array([[1, 2, 3, 4, 5, 6], 
              [7, 8, 9, 10, 20, 30]]) 

for i, j in np.nditer([x, y]):
    print (i, j)


1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
20 20
30 30
